### ISSUE TITLE
Formalize assocation types

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#111]
## Abstract
Now that the real nature of associations are getting together on all fronts, time for a grand refactor to accommodate:
- User-level modification
- OPS-level  modification (though possibly not different than user-level)
- Formalize observation, association candidate, and cross-observation associations
- Further prepare for the, yet-to-be-specified, Level2 associations

## TRAC references
- [x] [Level 3 Association Type Definitions](https://aeon.stsci.edu/ssb/trac/jwst/ticket/385)
- [x] [Isolate base Level classes from actual rules](https://aeon.stsci.edu/ssb/trac/jwst/ticket/314)

## ToDo
- [x] Factor into more distinct modules
- [x] Allow Associations to be instantiated without a member
- [x] Factor Association inside out
- [x] Factor out basic rule
