### ISSUE TITLE
MSASTATE of ALLOPEN and ALLCLOSE get different processing

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#2018]
# Issue
Prompted by [this discussion](https://github.com/STScI-JWST/jwst/issues/1188#issuecomment-381133421), need to modify rules to handle situations where the MSASTATE is ALLOPEN or ALLCLOSE.

# Resources
- #1188 
- [JSDP-469](https://jira.stsci.edu/browse/JSDP-469): MSASTATE needs to be apart of the association pool

# Implementation
Association creation and MSA states:

- If MSASTATE and MSAMETFL, then generate normal spec2/spec3 associations
- If no MSAMETFL and/or MSASTATE is `PRIMARYPARK_ALLOPEN`, and "grating == mirror", the `image2` associations will be created.
- Otherwise, no associations.

## ToDo
- [x] File issue against SDP to include MSASTATE in the association pool.
    There are actually two columns that will be added: MSASTATE and MSAMETFL 
- [x] bump version
- [x] documentation
- [x] tests
- [x] code
    - [x] Add a msa-specific constraint for valid spectral associations for level3.
    - [x] Add level2 check for no `msametfl` but for an `all-open` case for `image2` processing.
    - [x] Add level2 check to not include `all-open` in spec2 processing.
    - [x] `nrs_mimf` is making `spec3` associations. This is wrong. See `sdp/jw84600_fixed_pool` for `o035` and `o036`.
- [x] tests
- [x] documentation
- [x] bump version

**Comment by stscieisenhamer** [comment]
# Question
According to the keyword dictionary, the possible values of `MSASTATE` are:
- `LAUNCHLOCK_ALLCLOSED`
- `PRIMARYPARK_ALLOPEN`
- `PRIMARYPARK_ALLCLOSED`
- `PRIMARYPARK_CONFIGURED`

- [ ] First, are these really the values as opposed to the simple values that have been used?
- [ ] Second, I presume the only case where associations are to be created is `PRIMARYPARK_CONFIGURED`. Also, what is this value if the short-form is actually in use. Is it `CONFIGURED`?

**Comment by stscieisenhamer** [comment]
M.Swam reminds me that it is not clear that `MSASTATE` is sufficient and that the keyword with the actual msa config fits file is, so far with current test data, the only reliable means of knowing whether a config is given or not. To cover all basis, both keywords will be added to the pool.

**Comment by stscieisenhamer** [comment]
More info on exactly what should happen with the various states:

> The ALLOPEN configuration in MOS mode should only ever be used for imaging (i.e., grating=mirror).  If it's an on-sky observation, such as related to TA or astrometric calibration, then the level 2b processing will be via calwebb_image2, which for NIRSpec includes assign_wcs, flat field, and rectification.  If it's an observation with an internal lamp (used for certain calibrations, perhaps this is what you encountered?), then I think we only need processing through level 2a.  In either case, the actual MSA configuration file itself should not be needed by the pipeline.  The same should be true for an ALLCLOSED configuration in MOS mode, though that will likely be limited to internal lamp exposures only.
