### ISSUE TITLE
Rule: NIRSpec AUTOWAVE/AUTOFLAT

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#295]
Include AUTOWAVE/AUTOFLAT exposures into all NIRSpec associations.

**Comment by stscieisenhamer** [comment]
From @hbushouse, the definition of this issue is as follows:

> [There is a] requirement that says DMS shall associate contemporaneous calibration exposures with their respective science data. From what we can tell, the only such cal exposures that fall into this category are the NIRSpec AutoFlat and AutoWave exposures. They will almost certainly always be contained in the same ObsId as their science exposure counterparts, so there probably won’t be a AC_ID coming from PPS (unless they assign a single ObsId an Acid). In which case we will need an asn_generator rule that falls into the “self discovery” category and finds these by looking for exposures with EXP_TYPE of NRS_AUTOWAVE or NRS_AUTOFLAT that have the same ObsId as science exposures and also use the same FILTER and GRATING values as science exposures. I don’t know if they’ll also have the same TargId as the science exposures that they go with. Jeff Valenti was going to consult the NIRSpec team about what all the settings would be.

> All we have to do is include them in the member list of an association - the cal pipeline doesn’t do anything with them (at least not yet). But for the purpose of the cal pipeline knowing which exposures are which, I guess we should give them exptype attribute values of “AUTOWAVE” and “AUTOFLAT” in the ASN file.

**Comment by stscieisenhamer** [comment]
# Implementation
## ToDo
- [ ] Test setup
- [ ] Implement constraints: This applies to all spectrographic modes
- [ ] Set EXPTYPE in member list
- [ ] Confirm what TARGET will be expected.

## Constraints
For each NIRSpec spectrographic mode, add
- TBD

**Comment by hbushouse** [comment]
Auto wave/flat exposures will be specified on the same exposure line as a science exposure in the APT template, which means the science and wave/flat exposures will have the same:

program number
observation id
visit number
visit group number
sequence id
activity id

they will only differ in their exposure number. Additionally, because they come from the same observation and exposure specification line, they will also have the same target id/name, filter, and grating. They will simply differ in their exp_type and exposure number.

**Comment by stscieisenhamer** [comment]
Current implementation handles these constraints, mainly by the OBS_ID (candidate) constraint.
