### ISSUE TITLE
Refactor Level3 base rules

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#298]
Now that more info is coming about the more complicated observing modes, and how PPS is actually going to do things, a refactor of the Level3 base rules is in order.

**Comment by stscieisenhamer** [comment]
# Implementation
## ToDo
- [ ] Replace use of PNTGTYPE with EXP_TYPE
- [ ] Document/define EXPTYPE member attribute
- [ ] Remove DETECTOR as a generic constraint
- [ ] Move optical element constraints into the mode-specific rules
