### ISSUE TITLE
Ensure unique L3.5 associations

### ISSUE THREAD

**Issue by stscieisenhamer** [STScI-JWST/jwst#78]
This issue will resolve the track issue [Check for duplicate L3.5 associations with existing Candidate associations](https://aeon.stsci.edu/ssb/trac/jwst/ticket/325)
Steps to resolution:
- [x] Implement new pool specification for candidate identification (see below)
- [x] Ensure the 'cXXXX' and 'aXXXX' naming is occuring correctly #214
- [x] Ensure that the candidate and discovered associations only occur when not specifying an observation list. #221
- [x] Check for discovered candidate uniqueness
- [x] product names do not have the candidate id when in full mode #214

**Comment by stscieisenhamer** [comment]
In discussion with M.Swam/C.Rahmani, the Build6 pool format is deficient in specifying the candidates. Issue is that any single exposure can belong to multiple candidates, and at least one always being OBSERVATION. However, the candidate information is split into two columns. Both these columns would have to be a list, and the two lists would need to be kept in sync. Doable but not workable.
New format: Candidate info will now be one column, ASN_CANDIDATE. The contents of the column will be
```
[(id, type), (id, type), ...]
```
